### ISSUE TITLE
contents of repo

### ISSUE THREAD

**Issue by Beliavsky** [eatdust/futilities#1]
Could you describe the contents of the library in the Readme section? I would like to add the project to my list at https://github.com/Beliavsky/Fortran-code-on-GitHub

**Comment by cosmicinflation** [comment]
Yes, sure. It is a melting pot of various codes I am using for work, I'll do that but it'll take a bit of time at I need to at least a few explanation lines per module :)

**Comment by eatdust** [comment]
Yes, sure. I will in due time!
